### ISSUE TITLE
SARS-CoV-2 workflow comparison - kindly check if your work is represented correctly

### ISSUE THREAD

**Issue by thomasbtf** [niemasd/ViReflow#18]
Hello ViReflow Team,

I am from the University Hospital Essen, Germany, and we work extensively with SARS-CoV-2 in our research. We have also developed a [SARS-CoV-2 workflow](https://github.com/IKIM-Essen/uncovar). In preparation for the publication of our workflow, we have looked at several other SARS-CoV-2 related workflows, including your work. We will present this review in the publication and want to ensure that your work is represented as accurately as possible.

Moreover, there is currently little to no current overview of SARS-CoV-2 related workflows. Therefore, we have decided to make the above comparison publicly available [via this GitHub repository](https://github.com/IKIM-Essen/sars-cov-2-workflow-comparison). It contains a table with an overview of the functions of different SARS-CoV-2 workflows and the tools used to implement these functions.

We would like to give you the opportunity to correct any misunderstandings on our side. Please take a moment to make sure we are not misrepresenting your work or leaving out important parts of it by taking a look at [this overview table](https://github.com/IKIM-Essen/sars-cov-2-workflow-comparison/blob/main/workflow-overview.md). If you feel that something is missing or misrepresented, please feel free to give us feedback by contributing directly to the repository.

Thank you very much!

cc @alethomas

**Comment by niemasd** [comment]
Thank you for reaching out! The ViReflow paper, which has a comparison table as well, is currently under review at a journal, and while I don't think I can share the draft paper, I have extracted just the comparison table and GUI figure into a standalone Word document, which I hope will be helpful:

[vireflow_table_fig.docx](https://github.com/niemasd/ViReflow/files/8199580/vireflow_table_fig.docx)

Looking over the the table in your repository, please see the following comments / potential corrections:
* In the "**Seq. Technology**" column, ViReflow's row in the table only says "Illumina", but ViReflow is flexible to any form of amplicon sequencing (we *happened to use* Illumina sequencers for our amplicon sequencing). My understanding is that Nanopore technologies can also perform amplicon sequencing (e.g. [Calus *et al*., GigaScience 2018](https://doi.org/10.1093/gigascience/giy140)), so I think the cell should be updated to include "Nanopore" as well
* In the "**De Novo Assembly**" column, ViReflow's row in the table only says "coronaSPAdes, metaviralSPAdes, rnaviralSpades", but in addition to the various flavors of SPAdes, ViReflow now also supports MEGAHIT, minia, and Unicycler, so I think these should be added to the cell
* In the "**Lineage Calling**" column, ViReflow's row in the table only says "Pangolin", but ViReflow now also supports VirStrain, so I think this should be added to the cell
* In the "**Low Coverage Masking**" column, ViReflow's row in the table says "Yes", but I wonder if it would be good to change this to "bcftools consensus", as the low coverage masking is occurring directly in the bcftools consensus command that calls the consensus sequence. The current "Yes" is fine as well, though, as it's not a separate tool/step that's performing the masking (it's occurring directly within the consensus sequence calling)
* In the "**GUI / Report**" column, ViReflow's row in the table is empty ("-"), but ViReflow does indeed have a GUI (see screenshot in the Word document I attached above)

Thanks again for checking with us, and thank you for curating this wonderful comparison table! This is a great resource to have

**Comment by niemasd** [comment]
Ah, also, in the "**Comments**" column, V-pipe's row in the table says "for any virus, full haplotype reconstruction". I'm not sure if this is meant to be 2 separate items (i.e., "it works for any virus" and also "it supports full haplotype reconstruction") or if this is meant to be a single comment (i.e., "it can perform full haplotype reconstruction for any virus"), but if it's the former (2 separate items), ViReflow should also have "for any virus" as a comment, as it's generalized to any arbitrary virus

Also, I wonder if "dynamic compute resource allocation" should be a comment for ViReflow? That's the key selling point to its development: other pipelines already existed (as your comparison table demonstrates), but we wanted to build a pipeline that automatically dynamically scales computational resources depending on each specific run (e.g. running ViReflow with 100 vs. 1,000 samples is identical from the user's perspective, but AWS resources will automatically be scaled accordingly)

**Comment by thomasbtf** [comment]
Hi Niema,

thanks for the ViReflow comparison table and the detailed corrections! Seems like we misst ViralFlow in the comparison. Also, i've incorporated all of your suggestions in table (see https://github.com/IKIM-Essen/sars-cov-2-workflow-comparison/pull/18).

Thanks again for the contribution!
